package model.pojo;
// Generated Jul 2, 2022 8:28:04 PM by Hibernate Tools 4.3.1



/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String adress;

    public Company() {
    }

    public Company(String name, String adress) {
       this.name = name;
       this.adress = adress;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }




}


